Forsoft2_tentativa6/Forsoft2_tentativa6/Controllers/ListaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forsoft2_tentativa6.Controllers
{
    public class ListaController : Controller
    {
        // GET: Lista
        public ActionResult Recursos()
        {
            return RedirectToAction("Index","Recurso");
        }

        public ActionResult Usuarios()
        {
            return RedirectToAction("Index", "Usuario");
        }
        public ActionResult Home()
        {
            return RedirectToAction("Eventos");
        }
        public ActionResult Modalidades()
        {
            return Redirect("http://www2.stevent.com:8080/listarModalidades");
        }

        public ActionResult Equipes()
        {
            return Redirect("http://www2.stevent.com:8080/listarEquipes");
        }
        public ActionResult Eventos()
        {
            return Redirect("http://www2.stevent.com:8080/listarEventos");
        }
        public ActionResult Locais()
        {
            return Redirect("http://www2.stevent.com:8080/listarLocais");
        }
    }
}

Forsoft2_tentativa6/Forsoft2_tentativa6/Controllers/UsuarioAPIController.cs
using Forsoft2.Aplicacao;
using Forsoft2.Dominio;
using System.Collections.Generic;
using System.Web.Http;

namespace Forsoft2_tentativa6.Controllers
{
    public class UsuariosController : ApiController
    {
        // GET api/usuarioAPI/
        public List<Usuario> Get()
        {
            return new UsuarioAplicacao().ListarTodos();
        }

        // GET api/usuarioAPI/5
        public Usuario Get(int id)
        {
            return new UsuarioAplicacao().ListarPorID(id);
        }

        // POST api/usuarioAPI
        public void Post([FromBody]Usuario usuario)
        {
            var CatchUsuario = new UsuarioAplicacao();
            CatchUsuario.Salvar(usuario);
        }

        // PUT api/usuarioAPI/5
        public void Put(int id, [FromBody]Usuario usuario)
        {
            var CatchUsuario = new UsuarioAplicacao();
            CatchUsuario.Salvar(usuario);
        }

        // DELETE api/usuarioAPI/5
        public void Delete(int id)
        {
            new RecursoAplicacao().Excluir(id);
        }
    }
}

Forsoft2_tentativa6/Forsoft2_tentativa6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Forsoft2_tentativa6/Forsoft2_tentativa6/Views/Shared/_LayoutCadastroRecurso.cshtml
<html>
<head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <title>Cadastro Recursos</title>
</head>
<body>
    <nav id="nave">
        <ul>
            <li class="dropdown">
                <a href="#" class="dropbtn">Listas</a>
                <div class="dropdown-content">
                    @*<a href="#">Atletas</a>
            <a href="#">Equipe</a>
            <a href="#">Evento</a>
            <a href="#">Local</a>
            <a href="#">Recurso</a>*@
                    @Html.ActionLink("Atletas", "Atletas", "Lista")

                    @Html.ActionLink("Equipes", "Equipes", "Lista")

                    @Html.ActionLink("Eventos", "Eventos", "Lista")

                    @Html.ActionLink("Locais", "Locais", "Lista")

                    @Html.ActionLink("Recursos", "Recursos", "Lista")
                </div>
            </li>
            <li><a href="#news">Perfil</a></li>
            <li><a class="active" href="#home">Home</a></li>
            <li id="logo-nav"> <img src="http://i.imgur.com/vqRrYH2.png"></img> </li>
        </ul>
    </nav>
    <span id="login-box" name="formulario" onsubmit="return validaInfo()">
        <div id="goibada" class="login-box-interno">
            <div id="login-box-label">
                <h1> Recursos </h1>
            </div>
            <div class="login-form">
                <fieldset>
                    <legend>Dados do endereço:</legend>
                    <div class="control-group">
                        @RenderBody()
                        <div>
                            <label for="input-usuario">Local:</label>
                            <input name="Local" type="text" placeholder="Local" class="login-field" id="input-usuario" />
                        </div>
                    </div>
                </fieldset>
                <button type="submit" class="btn_login">Cadastrar</button>
            </div>
        </div>
    </span>
</body>
</html>

Forsoft2_tentativa6/Forsoft2_tentativa6/Views/Shared/_LayoutCadastroUsuario.cshtml
<html>
<head>
    <meta charset="UTF-8" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <script src="~/Script/script.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <!-- <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> -->
    <title>Cadastro</title>
</head>
<body>
    <nav id="nave">
        <ul>
            <li class="dropdown">
                <a href="#" class="dropbtn">Listas</a>
                <div class="dropdown-content">
                    @*<a href="#">Atletas</a>
            <a href="#">Equipe</a>
            <a href="#">Evento</a>
            <a href="#">Local</a>
            <a href="#">Recurso</a>*@
                    @Html.ActionLink("Atletas", "Atletas", "Lista")

                    @Html.ActionLink("Equipes", "Equipes", "Lista")

                    @Html.ActionLink("Eventos", "Eventos", "Lista")

                    @Html.ActionLink("Locais", "Locais", "Lista")

                    @Html.ActionLink("Recursos", "Recursos", "Lista")
                </div>
            </li>
            <li><a href="#news">Perfil</a></li>
            <li><a class="active" href="#home">Home</a></li>
            <li id="logo-nav"> <img src="http://i.imgur.com/vqRrYH2.png"></img> </li>
        </ul>
    </nav>
    <span id="login-box" name="formulario" onsubmit="return validaInfo()">
        <div id="goibada" class="login-box-interno">
            <div id="login-box-label">
                <h1> Novo Usuário </h1>
            </div>
            <div class="login-form">
                @RenderBody()
            </div>
        </div>
    </span>
</body>
</html>

Forsoft2_tentativa6/Forsoft2_tentativa6/Views/Shared/_LayoutListaRecurso.cshtml
<html>
<head>
    <meta charset="UTF-8" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <script src="~/Script/script.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <!-- <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> -->
    <title>Recursos</title>
</head>
<body>
    <nav id="nave">
        <ul>
            <li class="dropdown">
                <a href="#" class="dropbtn">Listas</a>
                <div class="dropdown-content">
                    @*<a href="#">Atletas</a>
            <a href="#">Equipe</a>
            <a href="#">Evento</a>
            <a href="#">Local</a>
            <a href="#">Recurso</a>*@
                    @Html.ActionLink("Atletas", "Atletas", "Lista")

                    @Html.ActionLink("Equipes", "Equipes", "Lista")

                    @Html.ActionLink("Eventos", "Eventos", "Lista")

                    @Html.ActionLink("Locais", "Locais", "Lista")

                    @Html.ActionLink("Recursos", "Recursos", "Lista")
                </div>
            </li>
            <li><a href="#news">Perfil</a></li>
            <li><a class="active" href="#home">Home</a></li>
            <li id="logo-nav"> <img src="http://i.imgur.com/vqRrYH2.png"></img> </li>
        </ul>
    </nav>
    <form id="login-box" name="formulario" onsubmit="return validaInfo()">
        <div id="goibada" class="login-box-interno">
            <div id="login-box-label">
                <h1> Lista recursos </h1>
            </div>
            <div class="login-form">
                <!--<button type="submit" class="btn_login">Cadastrar Novos recursos</button>-->
                @RenderBody()
            </div>
        </div>
    </form>
</body>
</html>

Forsoft2_tentativa6/Forsoft2_tentativa6/Views/Shared/_LayoutListaUsuario.cshtml
<html>
<head>
    <meta charset="UTF-8" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <script src="~/Script/script.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <!-- <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"> -->
    <title>Cadastro</title>
</head>
<body>
    <nav id="nave">
        <ul>
            <li class="dropdown">
                <a href="#" class="dropbtn">Listas</a>
                <div class="dropdown-content">
                    @*<a href="#">Atletas</a>
                    <a href="#">Equipe</a>
                    <a href="#">Evento</a>
                    <a href="#">Local</a>
                    <a href="#">Recurso</a>*@
                    @Html.ActionLink("Atletas", "Atletas", "Lista")
                    
                    @Html.ActionLink("Equipes", "Equipes", "Lista")
                    
                    @Html.ActionLink("Eventos", "Eventos", "Lista")
                    
                    @Html.ActionLink("Locais", "Locais", "Lista")
                    
                    @Html.ActionLink("Recursos", "Recursos", "Lista")
                </div>
            </li>
            <li><a href="#news">Perfil</a></li>
            <li><a class="active" href="#home">Home</a></li>
            <li id="logo-nav"> <img src="http://i.imgur.com/vqRrYH2.png"></img> </li>
        </ul>
    </nav>
    <form id="login-box" name="formulario" onsubmit="return validaInfo()">
        <div id="goibada" class="login-box-interno">
            <div id="login-box-label">
                <h1> Novos Usuários </h1>
            </div>
            <div class="login-form">
                <!--<button type="submit" class="btn_login">Cadastrar Novos Usuarios</button>-->
                @RenderBody()
            </div>
        </div>
    </form>
</body>
</html>

Forsoft2_tentativa6/Forsoft2_tentativa6/Views/Shared/_LayoutPageRecurso.cshtml
<html>
<head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <script src="js/script.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <title>Recursos</title>
</head>
<body onload="setarVisibilidade();">
    <nav id="nave">
        <ul>
            <li class="dropdown">
                <a href="#" class="dropbtn">Listas</a>
                <div class="dropdown-content">
                    <a href="#">@Html.ActionLink("Atletas", "Atletas", "Lista")</a>
                    <a href="#">@Html.ActionLink("Equipe", "Equipes", "Lista")</a>
                    <a href="#">@Html.ActionLink("Evento", "Eventos", "Lista")</a>
                    <a href="#">@Html.ActionLink("Local", "Locais", "Lista")</a>
                    <a href="#">@Html.ActionLink("Recurso", "Recursos", "Lista")</a>
                </div>
            </li>
            <li><a href="#news">Perfil</a></li>
            <li><a class="active" href="#home">Home</a></li>
            <li id="logo-nav"> <img src="http://i.imgur.com/vqRrYH2.png"></img> </li>
        </ul>
    </nav>
        <div id="goibada" class="login-box-interno">
            <div id="login-box-label">
                <h1> Recursos </h1>
            </div>
            <div class="login-form">
                <div style="height: 80%; width: 100%; overflow: auto;">
                    <table>
                        <tr>
                            <th>Nome</th>
                            <th>Disponibilidade</th>
                            <th>Descrição</th>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </table>
                </div>
                <button type="button" class="btn_login" onclick="abrirModal();">Cadastrar Novos Recursos</button>
            </div>
        </div>
    <!-- Estrutura do modal -->
    <div id="modal" class="modal-cadastro">
        <a class="close" onclick="abrirModal();">X</a>
        <form id="login-box" name="formulario" onsubmit="return validaInfo()">
            @RenderBody();
        </form>
    </div>
    <!-- Fim da estrutura do modal -->
</body>
</html>

Forsoft2_tentativa6/Forsoft2_tentativa6/Views/Shared/_LayoutPageRecursoNovo.cshtml
<html>
<head>
    <meta charset="UTF-8" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Script/script.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <title>Recursos</title>
</head>
<body onload="setarVisibilidade();">
    <nav id="nave">
        <ul>
            <li class="dropdown">
                <a href="#" class="dropbtn">Listas</a>
                <div class="dropdown-content">
                    <a href="#">@Html.ActionLink("Pessoa", "Usuarios", "Lista")</a>
                    <a href="#">@Html.ActionLink("Equipe", "Equipes", "Lista")</a>
                    <a href="#">@Html.ActionLink("Evento", "Eventos", "Lista")</a>
                    <a href="#">@Html.ActionLink("Modalidade", "Modalidades", "Lista")</a>
                    <a href="#">@Html.ActionLink("Local", "Locais", "Lista")</a>
                    <a href="#">@Html.ActionLink("Recurso", "Recursos", "Lista")</a>
                </div>
            </li>
            <li><a class="active" href="#home">@Html.ActionLink("Home", "Home", "Lista")</a></li>
            <li id="logo-nav">
                <img style="margin:0.1% 0% 0% 2%;" src="~/Imagens/logo1.png" />
            </li>
        </ul>
    </nav>
    @RenderBody()
</body>
</html>

Forsoft2_tentativa6/Forsoft2_tentativa6/Views/Shared/_LayoutPageUsuario.cshtml
<html>
<head>
    <meta charset="UTF-8" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Script/script.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <title>Usuários</title>
</head>
<body onload="setarVisibilidade();">
    <nav id="nave">
        <ul>
            <li class="dropdown">
                <a href="#" class="dropbtn">Listas</a>
                <div class="dropdown-content">
                    <a href="#">@Html.ActionLink("Pessoas", "Usuarios", "Lista")</a>
                    <a href="#">@Html.ActionLink("Equipe", "Equipes", "Lista")</a>
                    <a href="#">@Html.ActionLink("Evento", "Eventos", "Lista")</a>
                    <a href="#">@Html.ActionLink("Modalidade", "Modalidades", "Lista")</a>
                    <a href="#">@Html.ActionLink("Local", "Locais", "Lista")</a>
                    <a href="#">@Html.ActionLink("Recurso", "Recursos", "Lista")</a>
                </div>
            </li>
            <li><a class="active" href="#home">@Html.ActionLink("Home", "Home", "Lista")</a></li>
            <li id="logo-nav">
                 <img style="margin:0.1% 0% 0% 2%;" src="~/Imagens/logo1.png" />
            </li>
        </ul>
    </nav>
    @RenderBody()
    <!-- Fim da estrutura do modal -->
    
</body>
</html>